{% set name = "lens-vpr" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lens-vpr-{{ version }}.tar.gz
  sha256: a3bc89d56f8fdeb75cf698eddb7598a88be19cebe6fcc98c160d13101e749b12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<3.12
    - pytorch >=2.1.1
    - torchvision >=0.16.1
    - numpy >=1.26.2
    - pandas >=2.1.1
    - tqdm >=4.65.0
    - prettytable >=3.5.0
    - scikit-learn >=1.2.2
    - sinabs >=2.0.0
    - h5py >=3.10.0
    - imageio >=2.34.1
    - matplotlib-base >=3.8.2
    - pynmea2 >=1.19.0
    - scipy >=1.11.4
    - seaborn >=0.13.2
    - wandb >=0.16.2

test:
  imports:
    - lens
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AdamDHines/LENS
  summary: 'LENS: Locational Encoding with Neuromorphic Systems'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdamDHines
